services:
  backend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./../backend:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - MYSQL_HOST=docker-database-1
      - MYSQL_USER=footbee_user
      - MYSQL_PASSWORD=footbee_password
      - MYSQL_DB=footbee
    depends_on:
      - database
    expose:
      - "8080"

  database:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=footbee_user
      - MYSQL_PASSWORD=footbee_password
      - MYSQL_DATABASE=footbee
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
    
      - mysql_data:/var/lib/mysql
      - ./../sql/1-create_tables.sql:/docker-entrypoint-initdb.d/1-create_tables.sql
      - ./sql/2-load_data_docker.sql:/docker-entrypoint-initdb.d/2-load_data.sql
      - ./../sql/dataset:/var/lib/mysql-files

volumes:
  mysql_data:
