# Use a Node.js base image
FROM node:18-slim

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# # Build the frontend for production
# RUN npm run build

# Set the default command to serve the app
CMD ["npm", "start"]
